# Generated by Django 4.2.1 on 2023-05-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entryrecording', '0002_customer_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cutomer_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entryrecording.customerdata'),
        ),
    ]
